function createfigure(ZData1, YData1, XData1, CData1)
%CREATEFIGURE(ZDATA1, YDATA1, XDATA1, CDATA1)
%  ZDATA1:  patch zdata
%  YDATA1:  patch ydata
%  XDATA1:  patch xdata
%  CDATA1:  patch cdata

%  Auto-generated by MATLAB on 25-Feb-2017 23:04:05

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);

% Create patch
patch('Parent',axes1,'ZData',ZData1,'YData',YData1,'XData',XData1,...
    'FaceColor',[1 1 1],...
    'EdgeColor','flat',...
    'CData',CData1);

view(axes1,[134.9 25.2]);
grid(axes1,'on');
